### ISSUE TITLE
Support for missing button types

### ISSUE THREAD

**Issue by Aurasphere** [Aurasphere/facebot#14]
This should be very easy as well. We need to implement the new buttons on the platform. Here's the reference:

Buy: https://developers.facebook.com/docs/messenger-platform/send-api-reference/buy-button
Share: https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button
Log in: https://developers.facebook.com/docs/messenger-platform/account-linking/link-account
Log Out:  https://developers.facebook.com/docs/messenger-platform/account-linking/unlink-account

**Comment by alvin-reyes** [comment]
I already created the share button. I'll do the rest.

**Comment by Aurasphere** [comment]
Perfect, thank you!

**Comment by alvin-reyes** [comment]
This is included on the latest pull request.
